version: '3'
services:
  service-a:
    image: service-a
    ports:
      - "8081:8081"
    environment:
      - OUTBOUND_HOST_PORT=service-b:8082
      - JAEGER_SERVICE_NAME=service-a
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_LOG_SPANS=true
  service-b:
    image: service-b
    environment:
      - JAEGER_SERVICE_NAME=service-b
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_LOG_SPANS=true
  jaeger:
    image: docker.io/jaegertracing/all-in-one
    ports:
      - "16686:16686"
